<?xml version="1.0" ?>
<!DOCTYPE hitrecords [

<!ELEMENT hitrecords  (record)+>
<!--hitrecords has required child called record + indicates one or more instances of record required-->

<!ELEMENT record      (artist, title, length)>
<!--record element must have artist, title and length child elements in that order-->

<!ATTLIST record
  genre CDATA #REQUIRED                        
  >
<!--record must have an attribute called genre which must be character string data-->

<!ELEMENT artist     (#PCDATA)>
<!--artist element contains text string data-->

<!ATTLIST artist
  class (group | solo | duo) #REQUIRED
  gender (male | female | mixed) #REQUIRED
>
<!--artist has two attributes each with three possible values-->

<!ELEMENT title    (#PCDATA)>
<!--title element contains text string data-->

<!ELEMENT length (minutes, seconds)>
<!--the length element must have minutes and seconds child elements in that order-->

<!ELEMENT minutes  (#PCDATA)>
<!--minutes element contains text string data-->

<!ELEMENT seconds  (#PCDATA)>
<!--seconds element contains text string data-->
]>

<hitrecords>
    <record genre="Ska">
        <artist gender="male">Madness</artist>
        <title>Baggy Trousers</title>
        <length>
            <minutes>3</minutes>
            <seconds>30</seconds>
        </length>
    </record>
    <record genre="Pop">
        <artist class="solo" gender="female">Kate Bush</artist>
        <title>Babooshka</title>
        <length>
            <minutes>3</minutes>
            <seconds>50</seconds>
        </length>
    </record>
    <record genre="Soft Rock">
        <artist class="group" gender="male">Dire Straits</artist>
        <title>Romeo and Juliet</title>
        <length>
            <minutes>4</minutes>
            <seconds>15</seconds>
        </length>
    </record>
    <record genre="Pop">
        <artist class="solo" gender="male">David Bowie</artist>
        <title>Let's Dance</title>
        <length>
            <minutes>3</minutes>
            <seconds>35</seconds>
        </length>
    </record>
</hitrecords>